tap "homebrew/bundle"
tap "homebrew/core"
brew "go"
brew "mosh"
brew "neovim"
brew "opam"
brew "peco"
brew "python"
brew "reattach-to-user-namespace"
brew "the_silver_searcher"
brew "tmux"
brew "bash-completion"

