[[plugins]]
repo = 'fatih/vim-go'
on_ft = ['go']

[[plugins]]
repo = 'zchee/deoplete-go'
build = 'make'
on_ft = ['go']

[[plugins]]
repo = 'davidhalter/jedi-vim'
on_ft = 'python'
hook_add = '''
" let g:jedi#auto_initialization = 1
let g:jedi#auto_vim_configuration = 0
let g:jedi#smart_auto_mappings = 0
let g:jedi#completions_enabled = 0
'''

[[plugins]]
repo = 'zchee/deoplete-jedi'
on_ft = 'python'
# hook_add = '''
# let g:deoplete#sources#jedi#python_path = '/usr/bin/env python3'
# '''

[[plugins]]
repo = 'copy/deoplete-ocaml'
on_ft = 'ocaml'
