[[plugins]]
repo = 'Shougo/deoplete.nvim'
hook_add = 'let g:deoplete#enable_at_startup = 1'

[[plugins]]
repo = 'Shougo/unite.vim'
on_source = ['unite.vim']

[[plugins]]
repo = 'scrooloose/nerdcommenter'

[[plugins]]
repo = 'ntpeters/vim-better-whitespace'
hook_add = '''
let g:better_whitespace_enabled=1
let g:strip_whitespace_on_save=1
'''

[[plugins]]
repo = 'w0rp/ale'
hook_add = '''
let g:ale_sign_column_always = 1
let g:ale_set_highlights = 0

"let g:airline#extensions#ale#enabled = 1
'''

[[plugins]]
repo = 'thinca/vim-quickrun'
hook_add = '''
let g:quickrun_config = {
  \    'python': {
  \      'command': 'python3'
  \    },
  \ }

let g:quickrun_no_default_key_mappings = 1
nnoremap <Leader>x :QuickRun<CR>
'''
